apiVersion: apps/v1
kind: Deployment
metadata:
  name: play-store
  labels:
    app: play-store
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: play-store
  template:
    metadata:
      labels:
        app: play-store
    spec:
      containers:
      - image: alpine/curl
        name: play-store
