apiVersion: apps/v1
kind: Deployment
metadata:
  name: meet-stackit
  labels:
    app: meet-stackit
    scraper: meet-stackit-prom
spec:
  replicas: 3
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: meet-stackit
  template:
    metadata:
      labels:
        app: meet-stackit
        scraper: meet-stackit-prom
    spec:
      containers:
      - image: hoehne/meet-stackit:7
        name: meet-stackit
        env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secret-2
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret-2
                key: password
          - name: HOST 
            valueFrom:
              configMapKeyRef:
                name: db_config-2
                key: host
          - name: PORT 
            valueFrom:
              configMapKeyRef:
                name: db_config-2
                key: port
          - name: DB 
            valueFrom:
              configMapKeyRef:
                name: db_config-2
                key: db
        resources:
          requests:
            memory: 100Mi
            cpu: 250m
          limits:
            memory: 600Mi
            cpu: 2000m
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: actuator/health/livenessState
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: actuator/health/readinessState
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: meet-stackit-service
  labels:
    app: meet-stackit
    scraper: meet-stackit-prom

spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: meet-stackit
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meet-stackit-ingress
  labels:
    scraper: meet-stackit-prom
  annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /meet-stackit(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: meet-stackit-service
            port:
              number: 80
