apiVersion: apps/v1
kind: Deployment
metadata:
  name: play-store
  labels:
    app: play-store
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: play-store
  template:
    metadata:
      labels:
        app: play-store
    spec:
      containers:
      - image: alpine/curl
        name: play-store
        args:
          - /bin/sh
          - -c
          - while true; do sleep 600; done
        resources:
          requests:
            memory: 100Mi
            cpu: 200m
          limits:
            memory: 600Mi
            cpu: 500m
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
              - touch
              - /tmp/check
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
              - touch
              - /tmp/check
          initialDelaySeconds: 5
          periodSeconds: 5
