apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: meet-stackit
    scraper: meet-stackit-prom
  name: meet-stackit
spec:
  replicas: 3
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: meet-stackit
  template:
    metadata:
      labels:
        app: meet-stackit
        scraper: meet-stackit-prom
    spec:
      containers:
      - image: hoehne/meet-stackit:latest
        name: meet-stackit
        resources:
          requests:
            memory: 100Mi
            cpu: 250m
          limits:
            memory: 600Mi
            cpu: 2000m
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: actuator/health/livenessState
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: actuator/health/readinessState
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: meet-stackit
    scraper: meet-stackit-prom
  name: meet-stackit-service
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: meet-stackit
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meet-stackit-ingress
  labels:
    scraper: meet-stackit-prom
  annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /meet-stackit(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: meet-stackit-service
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meet-stackit-ingress-block-actuator
  labels:
    scraper: meet-stackit-prom
  annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /$2
     nginx.ingress.kubernetes.io/server-snippet: |
      location ~* "^/meet-stackit/actuator" {
          deny all;
          return 403;
        }
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /meet-stackit/actuator(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: meet-stackit-service
            port:
              number: 80
