apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: meet-stackit-alertmanager
spec:
  replicas: 2
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: meet-stackit

---

apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: meet-stackit-alertmanager-config
  labels:
    alertmanagerConfig: meet-stackit
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'meet-stackit-slack'

---
apiVersion: v1
kind: Service
metadata:
  name: meet-stackit-alertmanager
spec:
  type: LoadBalancer
  ports:
  - name: web
    protocol: TCP
    port: 9093
    targetPort: 9093
  - name: tcp-mesh
    protocol: TCP
    port: 9094
    targetPort: 9094
  - name: udp-mesh
    protocol: UDP
    port: 9094
    targetPort: 9094

  selector:
    alertmanager: meet-stackit-alertmanager
