apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: meet-stackit-alertmanager
spec:
  replicas: 2
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: meet-stackit

---

apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: meet-stackit-alertmanager-config
  labels:
    alertmanagerConfig: meet-stackit
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'meet-stackit-slack'

---
apiVersion: v1
kind: Service
metadata:
  name: meet-stackit-alertmanager
spec:
  type: LoadBalancer
  ports:
  - name: web
    nodePort: 30903
    port: 9093
    protocol: TCP
    targetPort: web
  selector:
    alertmanager: meet-stackit-alertmanager
