kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-config
  namespace: meet-stackit
  uid: 3d0938ad-d10f-452b-9012-60bcba62e5f1
  resourceVersion: '5531941'
  creationTimestamp: '2022-05-05T13:29:10Z'
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: v1
      time: '2022-05-05T13:29:10Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:prometheus.yaml: {}
data:
  prometheus.yaml: |-
    global:
      scrape_interval: 15s # By default, scrape targets every 15seconds. # Attach these labels to any time series or alerts when #communicating with external systems (federation, remote storage, #Alertmanager).
      external_labels:
        monitor: 'codelab-monitor'
    # Scraping Prometheus itself
    scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 5s
      static_configs:
      - targets: ['localhost:9090']
    - job_name: 'kubernetes-service-endpoints'
      metrics_path: /metrics
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: kubernetes_name
    - job_name: 'meet-stackit-service-endpoints'
      metrics_path: /actuator/prometheus
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: kubernetes_name
