apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqld-exporter
  labels:
    app: mysqld-exporter
spec:
  selector:
    matchLabels:
      app: mysqld-exporter
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9104"
      labels:
        app: mysqld-exporter
    spec:
      containers:
      - image: prom/mysqld-exporter:main
        name: mysqld-exporter
        env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password
          - name: HOST 
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: host
          - name: PORT 
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: port
          - name: DATA_SOURCE_NAME
            value: $(DB_USERNAME):$(DB_PASSWORD)@($(HOST):$(PORT))/
        resources:
          requests:
            memory: 100Mi
            cpu: 200m
          limits:
            memory: 600Mi
            cpu: 500m        
        ports:
        - containerPort: 9104
---
apiVersion: v1
kind: Service
metadata:
  name: mysqld-exporter-service
  labels:
    app: mysqld-exporter
    scraper: meet-stackit-prom
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 9104
  selector:
    app: mysqld-exporter
  type: ClusterIP
---