apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    prometheus: prometheus
spec:
  replicas: 2
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app: meet-stackit
  alerting:
    alertmanagers:
    - namespace: meet-stackit
      name: meet-stackit-alertmanager
      port: web
  ruleSelector:
    matchLabels:
      role: alert-rules
      prometheus: prometheus
#  remoteWrite:
#    - url: http://193.148.173.221:10908/api/v1/receive
