apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  ports:
  - name: web
    protocol: TCP
    port: 9090
    targetPort: 9090  
  selector:
    prometheus: prometheus

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /prometheus(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: prometheus
            port:
              number: 9090
