apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-configuration
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/JJDoneAway/meet-stackit-config.git
    targetRevision: HEAD
    path: prometheus
  destination: 
    server: https://kubernetes.default.svc
    namespace: meet-stackit

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
